sonar.projectKey=nutracore
sonar.projectName=NutraCore
sonar.sourceEncoding=UTF-8

sonar.sources=backend
sonar.tests=backend/tests

sonar.exclusions=backend/node_modules/**,backend/coverage/**,backend/docs/openapi.generated.json,frontend/**,node_modules/**
sonar.test.inclusions=backend/tests/**/*.test.js
sonar.coverage.exclusions=backend/tests/**,backend/scripts/**,backend/docs/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
